# Generated by Django 3.2.8 on 2021-11-26 03:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usercode', models.CharField(default='', max_length=130, null=True, unique=True, verbose_name='账号')),
                ('username', models.CharField(default='', max_length=130, null=True, unique=True, verbose_name='用户名')),
                ('password', models.CharField(help_text='Use to make_password or use to reset password form.', max_length=128, null=True, verbose_name='密码')),
                ('gender', models.BooleanField(choices=[(0, '女'), (1, '男')], default=None, null=True, verbose_name='性别')),
                ('email', models.EmailField(default='', max_length=254, null=True, unique=True, verbose_name='电子邮件')),
                ('phone', models.CharField(default='', max_length=128, null=True, unique=True, verbose_name='手机号')),
                ('visits', models.IntegerField(blank=True, default=1, null=True, verbose_name='访问次数')),
                ('profile_picture', models.URLField(blank=True, null=True, verbose_name='头像文件')),
                ('is_active', models.BooleanField(choices=[(0, '锁定'), (1, '正常')], default=None, null=True, verbose_name='用户状态')),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='上次访问时间')),
                ('date_joined', models.DateTimeField(auto_now=True, null=True, verbose_name='注册时间')),
            ],
            options={
                'verbose_name': '用户详情',
                'verbose_name_plural': '2.用户详情',
                'db_table': 'userinfo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(help_text='Use to make_password or use to reset password form.', max_length=128, null=True, verbose_name='密码')),
                ('email', models.EmailField(default='', max_length=254, null=True, unique=True, verbose_name='电子邮件')),
                ('phone', models.CharField(default='', max_length=128, null=True, unique=True, verbose_name='手机号')),
            ],
            options={
                'verbose_name': '用户基本信息',
                'verbose_name_plural': '1.用户',
                'db_table': 'users',
                'ordering': ('phone', 'email', 'password'),
                'managed': True,
            },
        ),
    ]
